# Generated by Django 3.1 on 2020-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
